[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = "https://yqrweefxltjprdgrkpxd.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxcndlZWZ4bHRqcHJkZ3JrcHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTUxMDAsImV4cCI6MjA3MjYzMTEwMH0.9Gg7PT57iwp2lE84S-7sg4j1t5srVvurx7M7RENnUmA"